cache:
  paths:
    - node_modules/

stages:
  - prepare
  - release

prepare_job:
  image: electronuserland/builder:wine
  stage: prepare
  script:
    - echo "PREPARE_JOB_ID=$CI_JOB_ID" >> variables.env
    - npm install
    - npm run build
    - npm run pack:mac
    - npm run pack:win
  rules:
    - if: $CI_COMMIT_TAG
  artifacts:
    paths:
      - "build/checktool-${CI_COMMIT_TAG}-mac.zip"
      - "build/checktool ${CI_COMMIT_TAG}.exe"
    reports:
      dotenv: variables.env

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: prepare_job
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "running release_job for $CI_COMMIT_TAG"
    - >
      release-cli create --name "Release $CI_COMMIT_TAG" --description "Created using the release-cli"
      --tag-name $CI_COMMIT_TAG --ref $CI_COMMIT_SHA
      --assets-links-name "macOS"
      --assets-links-url "https://gitlab.com/lionheart-group/tools/checking-tool/-/jobs/${PREPARE_JOB_ID}/artifacts/raw/build/checktool-${CI_COMMIT_TAG}-mac.zip"
      --assets-links-name "Windows"
      --assets-links-url "https://gitlab.com/lionheart-group/tools/checking-tool/-/jobs/${PREPARE_JOB_ID}/artifacts/raw/build/checktool%20${CI_COMMIT_TAG}.exe"
#   release:
#       name: 'Release $CI_COMMIT_TAG'
#       description: 'Created using the release-cli'
#       tag_name: '$CI_COMMIT_TAG'
#       ref: '$CI_COMMIT_SHA'
