cache:
  paths:
    - node_modules/

stages:
  - prepare
  - release

prepare_job:
  image: node:12.18.3
  stage: prepare
  script:
    - npm install
    - npm run build
    - npm run pack:mac
    - npm run pack:win
  rules:
    - if: $CI_COMMIT_TAG
  artifacts:
    paths:
      - 'build/checktool-$CI_COMMIT_TAG-mac.zip'
      - 'build/checktool $CI_COMMIT_TAG.exe'

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: prepare_job
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo 'running release_job for $TAG'
  release:
      name: 'Release $TAG'
      description: 'Created using the release-cli'
      tag_name: '$TAG'
      ref: '$CI_COMMIT_SHA'
