image: node:8.12

cache:
  paths:
  - node_modules/
  - .yarn

stages:
  - deploy

deploy_job:
  stage: deploy
  script:
    - yarn config set cache-folder .yarn
    - yarn install
    - yarn build
    - yarn package
  artifacts:
    paths:
      - CheckTool.app