default:
  image: node:12.18.3

variables:
  PACKAGE_VERSION: $(cat package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')

cache:
  paths:
    - node_modules/

stages:
  - deploy

job:
  stage: deploy
  script:
    - npm install
    - npm run build
    - npm run pack
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
      when: always
  artifacts:
    name: "v${PACKAGE_VERSION}"
    paths:
      - "build/checktool-${PACKAGE_VERSION}.dmg"
      - "build/checktool Setup ${PACKAGE_VERSION}.exe"
